---
- hosts: devops
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: 
          - python-apt
          - apache2
        state: present

    - name: Copy apache configuration
      copy:
        src: files/config/apache.conf
        dest: /etc/apache2/sites-available/000-default.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy index.html
      copy:
        src: files/site/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Create symbolic link for apache configuration
      file:
        src: /etc/apache2/sites-available/000-default.conf
        dest: /etc/apache2/sites-enabled/000-default.conf
        state: link

    - name: Restart Apache2 service
      service:
        name: apache2
        state: restarted
